emails = ['gablop6543@gmail.com']
senhas = ['bolarede792']

# Dados das glicemias e Dados dos horários para serem colocados no gráfico.
glicemias_01 = []
glicemias_01_hora = []
glicemias_02 = []
glicemias_02_hora = []
glicemias_03 = []
glicemias_03_hora = []
glicemias_04 = []
glicemias_04_hora = []
glicemias_05 = []
glicemias_05_hora = []
glicemias_06 = []
glicemias_06_hora = []
glicemias_07 = []
glicemias_07_hora = []
glicemias_08 = []
glicemias_08_hora = []
glicemias_09 = []
glicemias_09_hora = []
# Dados das glicemias e Dados dos horários para serem colocados no gráfico.
